CREATE TABLE IF NOT EXISTS public.production_history (
    id integer GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 2147483647
        CACHE 1
    ),
    record_date date NOT NULL,
    sand_stock int NOT NULL,
    copper_stock int NOT NULL,
    screens_produced int NOT NULL
);