  const styles = {
    container: {
      display: "flex",
      minHeight: "100vh",
      backgroundColor: "#f5f5f5",
      fontFamily: "Arial, sans-serif",
    },
    sidebar: {
      width: "250px",
      backgroundColor: "white",
      boxShadow: "2px 0 4px rgba(0,0,0,0.1)",
      padding: "24px 0",
      position: "fixed" as const,
      height: "100vh",
      overflowY: "auto" as const,
    },
    sidebarHeader: {
      padding: "0 24px 24px 24px",
      borderBottom: "1px solid #e0e0e0",
      marginBottom: "24px",
    },
    sidebarTitle: {
      fontSize: "20px",
      fontWeight: "bold",
      color: "#333",
      margin: 0,
    },
    sidebarNav: {
      padding: "0 12px",
    },
    navItem: {
      display: "flex",
      alignItems: "center",
      gap: "12px",
      padding: "12px 16px",
      margin: "4px 0",
      backgroundColor: "transparent",
      border: "none",
      borderRadius: "8px",
      fontSize: "14px",
      fontWeight: "500",
      color: "#666",
      cursor: "pointer",
      width: "100%",
      textAlign: "left" as const,
    },
    navItemActive: {
      backgroundColor: "#007bff",
      color: "white",
    },
    mainContent: {
      marginLeft: "250px",
      flex: 1,
      padding: "24px",
    },
    maxWidth: {
      maxWidth: "1400px",
      margin: "0 auto",
    },
    header: {
      backgroundColor: "white",
      borderRadius: "8px",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      padding: "24px",
      marginBottom: "24px",
    },
    title: {
      fontSize: "32px",
      fontWeight: "bold",
      color: "#333",
      marginBottom: "8px",
      margin: 0,
    },
    subtitle: {
      fontSize: "16px",
      color: "#666",
      margin: 0,
    },
    refreshButton: {
      padding: "8px 16px",
      backgroundColor: "#28a745",
      color: "white",
      border: "none",
      borderRadius: "4px",
      fontSize: "14px",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: "8px",
      marginTop: "16px",
    },
    tabs: {
      display: "flex",
      borderBottom: "2px solid #e0e0e0",
      marginBottom: "24px",
    },
    tab: {
      padding: "12px 24px",
      backgroundColor: "transparent",
      border: "none",
      fontSize: "16px",
      fontWeight: "500",
      cursor: "pointer",
      borderBottom: "2px solid transparent",
      color: "#666",
    },
    activeTab: {
      color: "#007bff",
      borderBottomColor: "#007bff",
    },
    topControls: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "24px",
      flexWrap: "wrap" as const,
      gap: "16px",
    },
    viewModeGroup: {
      display: "flex",
      flexDirection: "column" as const,
    },
    filterGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
      gap: "16px",
      alignItems: "end",
    },
    filterGroup: {
      display: "flex",
      flexDirection: "column" as const,
    },
    label: {
      fontSize: "14px",
      fontWeight: "500",
      color: "#555",
      marginBottom: "4px",
    },
    input: {
      padding: "8px 12px",
      border: "1px solid #ddd",
      borderRadius: "4px",
      fontSize: "14px",
    },
    select: {
      padding: "8px 12px",
      border: "1px solid #ddd",
      borderRadius: "4px",
      fontSize: "14px",
      backgroundColor: "white",
    },
    button: {
      padding: "8px 16px",
      backgroundColor: "#007bff",
      color: "white",
      border: "none",
      borderRadius: "4px",
      fontSize: "14px",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    buttonDisabled: {
      backgroundColor: "#ccc",
      cursor: "not-allowed",
    },
    filterSummary: {
      marginTop: "16px",
      padding: "12px",
      backgroundColor: "#e3f2fd",
      borderRadius: "4px",
      fontSize: "14px",
      color: "#1565c0",
    },
    cardsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
      gap: "24px",
      marginBottom: "24px",
    },
    card: {
      backgroundColor: "white",
      borderRadius: "8px",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      padding: "20px",
      opacity: 1,
    },
    cardLoading: {
      opacity: 0.5,
    },
    cardHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "12px",
    },
    cardTitle: {
      fontSize: "14px",
      fontWeight: "500",
      color: "#666",
      margin: 0,
    },
    cardValue: {
      fontSize: "28px",
      fontWeight: "bold",
      color: "#333",
      marginBottom: "4px",
    },
    cardDescription: {
      fontSize: "12px",
      color: "#888",
      marginBottom: "8px",
    },
    cardChange: {
      fontSize: "12px",
      marginTop: "4px",
    },
    tableContainer: {
      backgroundColor: "white",
      borderRadius: "8px",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      padding: "24px",
      overflowX: "auto" as const,
    },
    tableTitle: {
      fontSize: "20px",
      fontWeight: "bold",
      color: "#333",
      marginBottom: "16px",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse" as const,
      fontSize: "14px",
    },
    th: {
      backgroundColor: "#f8f9fa",
      padding: "12px",
      textAlign: "left" as const,
      fontWeight: "600",
      color: "#555",
      borderBottom: "2px solid #dee2e6",
    },
    td: {
      padding: "12px",
      borderBottom: "1px solid #dee2e6",
    },
    trHover: {
      backgroundColor: "#f8f9fa",
    },
    alertCard: {
      backgroundColor: "#fff3cd",
      border: "1px solid #ffeaa7",
      borderRadius: "8px",
      padding: "16px",
      marginBottom: "16px",
    },
    alertTitle: {
      fontSize: "16px",
      fontWeight: "600",
      color: "#856404",
      marginBottom: "8px",
      display: "flex",
      alignItems: "center",
      gap: "8px",
    },
    alertText: {
      fontSize: "14px",
      color: "#856404",
      margin: 0,
    },
  };

  export default styles