CREATE TABLE "raw_materials" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "quantity" integer NOT NULL
);

CREATE TABLE "screen_orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" integer NOT NULL,
  "order_date" date NOT NULL,
  "unit_price" integer NOT NULL,
  "status_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "amount_paid" integer
);

CREATE TABLE "purchase_orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "shipment_id" integer,
  "quantity" integer NOT NULL,
  "quantity_delivered" integer,
  "order_date" date NOT NULL,
  "unit_price" integer NOT NULL,
  "seller_bank_account" varchar(50) NOT NULL,
  "origin" varchar(50) NOT NULL,
  "status_id" integer NOT NULL,
  "raw_materials_id" integer,
  "equipment_order" bool
);

CREATE TABLE "order_status" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" integer NOT NULL,
  "unit_price" integer NOT NULL
);

CREATE TABLE "equipment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parameters_id" integer NOT NULL,
  "is_producing" boolean NOT NULL,
  "is_available" boolean NOT NULL,
  "purchase_orders_id" integer
);

CREATE TABLE "equipment_parameters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "input_sand_kg" integer NOT NULL,
  "input_copper_kg" integer NOT NULL,
  "output_screens_day" integer NOT NULL
);

CREATE TABLE "bank_details" (
  "account_number" varchar(50) PRIMARY KEY
);

ALTER TABLE "equipment" ADD FOREIGN KEY ("parameters_id") REFERENCES "equipment_parameters" ("id");

ALTER TABLE "screen_orders" ADD FOREIGN KEY ("status_id") REFERENCES "order_status" ("id");

ALTER TABLE "screen_orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("status_id") REFERENCES "order_status" ("id");

ALTER TABLE "purchase_orders" ADD FOREIGN KEY ("raw_materials_id") REFERENCES "raw_materials" ("id");

ALTER TABLE "equipment" ADD FOREIGN KEY ("purchase_orders_id") REFERENCES "purchase_orders" ("id");
