name: Deploy Backend API
on:
  workflow_dispatch: 
    
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Get EC2 public IP from repository variable
        id: tf_output
        run: |
          echo "EC2_IP=${{ vars.EC2_PUBLIC_DNS }}" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
      
      - name: Copy start.sh script to EC2
        working-directory: backend
        run: |
          scp -o StrictHostKeyChecking=no -i ../ec2_key.pem ./start.sh ubuntu@$EC2_IP:~/start.sh

      - name: Clean up old build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
          rm -rf build/*
          mkdir -p build
          EOF

      - name: Build and publish .NET application
        working-directory: backend
        run: |
          dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true

      - name: Copy application to EC2
        working-directory: backend
        run: |
          scp -o StrictHostKeyChecking=no -i ../ec2_key.pem ./bin/Release/net9.0/linux-x64/publish/* ubuntu@$EC2_IP:~/build/

      - name: Start application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
          chmod +x ~/start.sh
          bash ~/start.sh
          EOF